# Generated by Django 4.2.4 on 2023-08-23 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_service_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
        migrations.AlterField(
            model_name='services',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.client'),
        ),
        migrations.CreateModel(
            name='AddClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=50)),
                ('handle_by', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=50)),
                ('acc_no', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=50)),
                ('gst', models.CharField(max_length=15)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.client')),
            ],
            options={
                'db_table': 'providers',
            },
        ),
    ]
